# Generated by Django 4.2.18 on 2025-03-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_Profile',
        ),
    ]
