# Generated by Django 4.2.18 on 2025-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='address',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='email_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
