# Generated by Django 4.2.19 on 2025-04-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0002_remove_user_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
